const KEY='tamaouz_requests';
const statuses=['Submitted','Under Review','In Progress','Ready for Review','Completed'];
const translations={en:{newRequest:'New Request',eyebrow:'STUDENT DASHBOARD',title:'My Requests',subtitle:'Track your academic requests and their current status.',create:'Create New Request',emptyTitle:'No requests yet',emptyText:'Your submitted requests will appear here.',start:'Start a Request',student:'Student',workplace:'University / Workplace',deadline:'Deadline',submitted:'Submitted',notSpecified:'Not specified',noMatch:'No matching requests',changeSearch:'Try changing the search or status filter.',status:{Submitted:'Submitted','Under Review':'Under Review','In Progress':'In Progress','Ready for Review':'Ready for Review',Completed:'Completed'}},ar:{newRequest:'طلب جديد',eyebrow:'لوحة الطالب',title:'طلباتي',subtitle:'تابع طلباتك الأكاديمية وحالتها الحالية.',create:'إنشاء طلب جديد',emptyTitle:'لا توجد طلبات بعد',emptyText:'ستظهر طلباتك المرسلة هنا.',start:'ابدأ طلبًا',student:'الطالب',workplace:'الجامعة / جهة العمل',deadline:'الموعد النهائي',submitted:'تاريخ الإرسال',notSpecified:'غير محدد',noMatch:'لا توجد طلبات مطابقة',changeSearch:'جرّب تغيير البحث أو فلتر الحالة.',status:{Submitted:'تم الإرسال','Under Review':'قيد المراجعة','In Progress':'قيد التنفيذ','Ready for Review':'جاهز للمراجعة',Completed:'مكتمل'}}};
let lang=localStorage.getItem('tamaouz_language')||'en';
const tr=k=>translations[lang][k]??k;
function getRequests(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function saveRequests(items){localStorage.setItem(KEY,JSON.stringify(items))}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function card(r,admin=false){return `<article class="request-card"><div class="request-head"><div><div class="request-id">${esc(r.requestId||r.id)}</div><p>${esc(r.requestType||r.type)}</p></div>${admin?`<select class="status-select" data-id="${esc(r.requestId||r.id)}">${statuses.map(s=>`<option ${s===r.status?'selected':''}>${esc(translations[lang].status[s])}</option>`).join('')}</select>`:`<span class="badge">${esc(translations[lang].status[r.status]||r.status)}</span>`}</div><div class="meta"><div><small>${tr('student')}</small><strong>${esc(r.fullName)}</strong></div><div><small>${tr('workplace')}</small><strong>${esc(r.workplace)}</strong></div><div><small>${tr('deadline')}</small><strong>${esc(r.deadline||tr('notSpecified'))}</strong></div><div><small>${tr('submitted')}</small><strong>${esc(r.createdAt||'')}</strong></div></div></article>`}
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.dir=document.documentElement.dir;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));const b=document.getElementById('languageToggle');if(b)b.textContent=lang==='ar'?'English':'العربية';renderStudent();}
function renderStudent(){const list=document.getElementById('requestList'),empty=document.getElementById('empty');if(!list)return;const items=getRequests();empty.hidden=items.length>0;list.innerHTML=items.map(r=>card(r)).join('')}
function renderAdmin(){const list=document.getElementById('adminList');if(!list)return;const q=(document.getElementById('search')?.value||'').toLowerCase(),filter=document.getElementById('statusFilter')?.value||'';const items=getRequests().filter(r=>(!filter||r.status===filter)&&(!q||`${r.requestId||r.id} ${r.fullName} ${r.requestType||r.type}`.toLowerCase().includes(q)));list.innerHTML=items.length?items.map(r=>card(r,true)).join(''):`<div class="empty"><h2>${tr('noMatch')}</h2><p>${tr('changeSearch')}</p></div>`;list.querySelectorAll('.status-select').forEach(s=>s.addEventListener('change',e=>{const all=getRequests();const r=all.find(x=>(x.requestId||x.id)===e.target.dataset.id);if(r){const selected=Array.from(e.target.options).find(o=>o.selected);r.status=statuses.find(x=>translations[lang].status[x]===selected.text)||e.target.value;saveRequests(all);renderAdmin()}}))}
if(document.getElementById('languageToggle'))document.getElementById('languageToggle').addEventListener('click',()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('tamaouz_language',lang);applyLanguage();if(document.getElementById('adminList'))renderAdmin()});
if(document.getElementById('requestList'))applyLanguage();
if(document.getElementById('adminList')){document.getElementById('search').addEventListener('input',renderAdmin);document.getElementById('statusFilter').addEventListener('change',renderAdmin);applyLanguage();renderAdmin()}
