const API_URL='https://script.google.com/macros/s/AKfycbw4GeV2ZDrYcPq8fYSuHhWtold8OUseRLU_mXBOztprFH_L4Q63ZiDuQYOwtZ9GaEz2/exec';
let lang=localStorage.getItem('tamaouz_language')||'en';
const translations={en:{newRequest:'New Request',eyebrow:'STUDENT DASHBOARD',title:'Track your request',subtitle:'Enter your request ID and the email used when you submitted it.',create:'Create New Request',requestId:'Request ID',email:'Email Address',track:'Track Request',loading:'Checking your request...',notFound:'Request not found or the email does not match.',network:'Unable to connect to the request service. Please try again.',student:'Student',type:'Request Type',workplace:'University / Workplace',deadline:'Deadline',submitted:'Submitted',project:'Research / Project Title',pages:'Pages',references:'References',citation:'Referencing Style',topic:'Research Question / Topic',instructions:'Special Instructions',details:'Request Details',status:{Submitted:'Submitted','Under Review':'Under Review','In Progress':'In Progress','Ready for Review':'Ready for Review',Completed:'Completed'},statusHelp:'Current status',steps:['Submitted','Under Review','In Progress','Ready for Review','Completed']},ar:{newRequest:'طلب جديد',eyebrow:'لوحة الطالب',title:'متابعة الطلب',subtitle:'أدخل رقم الطلب والبريد الإلكتروني المستخدم عند إرسال الطلب.',create:'إنشاء طلب جديد',requestId:'رقم الطلب',email:'البريد الإلكتروني',track:'متابعة الطلب',loading:'جارٍ البحث عن الطلب...',notFound:'لم يتم العثور على الطلب أو أن البريد الإلكتروني غير مطابق.',network:'تعذر الاتصال بخدمة الطلبات. يرجى المحاولة مرة أخرى.',student:'الطالب',type:'نوع الطلب',workplace:'الجامعة / جهة العمل',deadline:'الموعد النهائي',submitted:'تاريخ الإرسال',project:'عنوان البحث / المشروع',pages:'عدد الصفحات',references:'عدد المراجع',citation:'نمط التوثيق',topic:'سؤال البحث / الموضوع',instructions:'تعليمات خاصة',details:'تفاصيل الطلب',status:{Submitted:'تم الإرسال','Under Review':'قيد المراجعة','In Progress':'قيد التنفيذ','Ready for Review':'جاهز للمراجعة',Completed:'مكتمل'},statusHelp:'الحالة الحالية',steps:['تم الإرسال','قيد المراجعة','قيد التنفيذ','جاهز للمراجعة','مكتمل']}};
const tr=k=>translations[lang][k]??translations.en[k]??k;
const esc=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.dir=document.documentElement.dir;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));const b=document.getElementById('languageToggle');if(b)b.textContent=lang==='ar'?'English':'العربية';}
function fmtDate(v){if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return esc(v);return new Intl.DateTimeFormat(lang==='ar'?'ar-SA':'en-US',{year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d);}
function renderRequest(r){const statuses=translations[lang].steps;const index=Math.max(0,translations.en.steps.indexOf(r.status));const statusText=translations[lang].status[r.status]||r.status||'—';const dynamic=Object.entries(r.dynamicRequirements||{}).filter(([,v])=>String(v||'').trim()).map(([k,v])=>`<div><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('');document.getElementById('requestResult').innerHTML=`<article class="request-card"><div class="result-head"><div><span class="request-id">${esc(r.requestId)}</span><h2>${esc(r.projectTitle||r.requestType||'Request')}</h2></div><span class="badge">${esc(statusText)}</span></div><div class="status-block"><p>${esc(tr('statusHelp'))}</p><div class="status-line">${statuses.map((s,i)=>`<div class="status-step ${i<=index?'done':''} ${i===index?'current':''}"><span>${i+1}</span><small>${esc(s)}</small></div>`).join('')}</div></div><div class="details-grid"><div><small>${esc(tr('student'))}</small><strong>${esc(r.fullName)}</strong></div><div><small>${esc(tr('type'))}</small><strong>${esc(r.requestType)}</strong></div><div><small>${esc(tr('workplace'))}</small><strong>${esc(r.workplace)}</strong></div><div><small>${esc(tr('submitted'))}</small><strong>${fmtDate(r.createdAt)}</strong></div><div><small>${esc(tr('deadline'))}</small><strong>${esc(r.deadline||'—')}</strong></div><div><small>${esc(tr('pages'))}</small><strong>${esc(r.pages||'—')}</strong></div><div><small>${esc(tr('references'))}</small><strong>${esc(r.references||'—')}</strong></div><div><small>${esc(tr('citation'))}</small><strong>${esc(r.citation||'—')}</strong></div></div><div class="text-block"><h3>${esc(tr('topic'))}</h3><p>${esc(r.topic||'—')}</p></div>${dynamic?`<div class="dynamic-block"><h3>${esc(tr('details'))}</h3><div class="dynamic-grid">${dynamic}</div></div>`:''}${r.instructions?`<div class="text-block"><h3>${esc(tr('instructions'))}</h3><p>${esc(r.instructions)}</p></div>`:''}</article>`;document.getElementById('requestResult').hidden=false;}
function lookupViaJsonp(id,email){return new Promise((resolve,reject)=>{const callback='tamaouzCallback_'+Date.now()+'_'+Math.floor(Math.random()*10000);const script=document.createElement('script');let timer;const cleanup=()=>{clearTimeout(timer);delete window[callback];if(script.parentNode)script.parentNode.removeChild(script);};window[callback]=data=>{cleanup();resolve(data);};script.onerror=()=>{cleanup();reject(new Error('NETWORK'));};script.src=API_URL+'?action=getRequest&requestId='+encodeURIComponent(id)+'&email='+encodeURIComponent(email)+'&callback='+encodeURIComponent(callback)+'&_='+Date.now();timer=setTimeout(()=>{cleanup();reject(new Error('NETWORK'));},15000);document.head.appendChild(script);});}
async function lookup(e){e.preventDefault();const form=e.currentTarget;const id=document.getElementById('requestId').value.trim();const email=document.getElementById('email').value.trim();const msg=document.getElementById('message');const result=document.getElementById('requestResult');if(!form.checkValidity()){form.reportValidity();return;}msg.hidden=false;msg.className='message loading';msg.textContent=tr('loading');result.hidden=true;try{const data=await lookupViaJsonp(id,email);if(!data.ok){msg.className='message error-message';msg.textContent=data.error||tr('notFound');return;}msg.hidden=true;renderRequest(data.request);}catch(err){msg.className='message error-message';msg.textContent=tr('network');}}
document.getElementById('languageToggle').addEventListener('click',()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('tamaouz_language',lang);applyLanguage();});
document.getElementById('lookupForm').addEventListener('submit',lookup);
applyLanguage();
const params=new URLSearchParams(location.search);if(params.get('requestId'))document.getElementById('requestId').value=params.get('requestId');